### ISSUE TITLE
When running bin/up : overleaf_key.pem: No such file or directory

### ISSUE THREAD

**Issue by AdrienJarretier** [overleaf/toolkit#57]
Hi,

When following the [Quick-Start Guide](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md)

I get an error at the [Starting Up](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md#starting-up) step

## Steps to Reproduce

1. Follow the [Quick-Start Guide](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md).
2. Until trying to run `bin/up`

## Expected Behaviour
should see some log output from the docker containers, indicating that the containers are running

## Observed Behaviour
I get `realpath: config/nginx/certs/overleaf_key.pem: No such file or directory`

## Context
I'm following the [Quick-Start Guide](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md) to try and get Overleaf running on a local VM.

## Technical Info

Here's the output of `bin/doctor`

```
====== Overleaf Doctor ======
- Host Information
    - Linux
    - Output of 'lsb_release -a':
            No LSB modules are available.
            Distributor ID:     Ubuntu
            Description:        Ubuntu 20.04.2 LTS
            Release:    20.04
            Codename:   focal
- Dependencies
    - bash
        - status: present
        - version info: 5.0.17(1)-release
    - docker
        - status: present
        - version info: Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
    - docker-compose
        - status: present
        - version info: docker-compose version 1.25.0, build unknown
    - realpath
        - status: present
        - version info: realpath (GNU coreutils) 8.30
    - perl
        - status: present
        - version info: 5.030000
    - awk
        - status: present
        - version info: GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)
    - openssl
        - status: present
        - version info: OpenSSL 1.1.1f  31 Mar 2020
- Docker Daemon
    - status: DOWN !
====== Configuration ======
- config/version
    - status: present
    - version: 2.6.1
- config/overleaf.rc
    - status: present
    - values
        - SHARELATEX_DATA_PATH: data/sharelatex
        - SERVER_PRO: false
        - SHARELATEX_PORT: 80
        - MONGO_ENABLED: true
        - MONGO_DATA_PATH: data/mongo
        - REDIS_ENABLED: true
        - REDIS_DATA_PATH: data/redis
        - NGINX_ENABLED: false
        - NGINX_CONFIG_PATH: config/nginx/nginx.conf
        - TLS_PRIVATE_KEY_PATH: config/nginx/certs/overleaf_key.pem
        - TLS_CERTIFICATE_PATH: config/nginx/certs/overleaf_certificate.pem
- config/variables.env
    - status: present
====== Warnings ======
! Docker daemon is not running
====== End ======
```

As you can see it is Ubuntu 20.04.2 LTS, it's a clean VM where I just installed Ubuntu server,
I haven't touched the config files so `NGINX_ENABLED` is still set to `false`

**Comment by jerrylususu** [comment]
I had the same problem. Commenting out the file path in the TLS section in `/config/overleaf.rc` seems to fix the problem.

```
# TLS proxy configuration (optional)
# See documentation in doc/tls-proxy.md
NGINX_ENABLED=false
# NGINX_CONFIG_PATH=config/nginx/nginx.conf
# TLS_PRIVATE_KEY_PATH=config/nginx/certs/overleaf_key.pem
# TLS_CERTIFICATE_PATH=config/nginx/certs/overleaf_certificate.pem
# TLS_PORT=443
```

**Comment by amaralc** [comment]
I had the same problem and @jerrylususu  solution has worked for me too.

**Comment by lan94** [comment]
I had the same problem. Seems like the script expects that the certs are generated when it is starting. When reading the init script it shows that you can generate these certs with "--tls". So I did following:

`user@host:~/overleaf$ rm -rf ./config/*
user@host:~/overleaf$ bin/init --tls
user@host:~/overleaf$ sudo bin/up`

This should work without commenting out some configs.

**Comment by mserranom** [comment]
Should be fixed by https://github.com/overleaf/toolkit/pull/61

**Comment by vivek9patel** [comment]
Hi @mserranom, I am following the [Quick-start guide](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md) but still facing the same issue:

<img width="479" alt="Screenshot 2023-02-12 at 1 02 36 AM" src="https://user-images.githubusercontent.com/50517245/218299771-63ebd1ce-3a79-467c-902b-1896b7fa543d.png">

**Comment by kuba108** [comment]
Hi, I had same issue. 
Looks like creating directories under data helps. I followed errors and created sharelatex, mongo and redis:

```
mkdir data/sharelatex
mkdir data/mongo
mkdir data/redis
```

Then I ran bin/up and it works!

**Comment by gourab5139014** [comment]
@kuba108 Thanks! Besides creating those directories, I had to create data/git-bridge too

```mkdir data/git-bridge```

**Comment by mserranom** [comment]
@vivek9patel @kuba108 @gourab5139014 thanks, I'll look into it.
